CONFIG_RGBLED_WIDGET=y

CONFIG_RGBLED_WIDGET_BATTERY_SHOW_SELF=y

CONFIG_RGBLED_WIDGET_BATTERY_BLINK_MS=1000
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=80
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_HIGH=7

CONFIG_RGBLED_WIDGET_BATTERY_COLOR_MEDIUM=3

CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_LOW=20
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_LOW=1

CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_CRITICAL=1

CONFIG_RGBLED_WIDGET_INTERVAL_MS=1000

CONFIG_RGBLED_WIDGET_CONN_BLINK_MS=250
CONFIG_RGBLED_WIDGET_CONN_COLOR_CONNECTED=2
CONFIG_RGBLED_WIDGET_CONN_COLOR_ADVERTISING=4
CONFIG_RGBLED_WIDGET_CONN_COLOR_DISCONNECTED=1

#CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y
#CONFIG_RGBLED_WIDGET_LAYER_5_COLOR=1
